[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

allow = [
    "Apache-2.0",
    #"BSD-2-Clause", # OK but currently unused; commenting to prevent warning
    "BSD-3-Clause",
    "BSL-1.0",
    #"CC0-1.0",  # OK but currently unused; commenting to prevent warning
    "ISC",
    "MIT",
    "OpenSSL",
    "Unlicense",
    #"Zlib",  # OK but currently unused; commenting to prevent warning
]

exceptions = [
    { name = "unicode-ident", version = "1.0.4", allow = ["MIT", "Apache-2.0", "Unicode-DFS-2016"] },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[bans]
# Deny multiple versions or wildcard dependencies.
multiple-versions = "deny"
wildcards = "deny"

skip= [
    { name = "base64", version = "0.21" },
    { name = "http", version = "0.2" },
    { name = "http-body", version = "0.4" },
]

skip-tree = [
    # windows-sys is not a direct dependency. mio and schannel
    # are using different versions of windows-sys. we skip the
    # dependency tree because windows-sys has many sub-crates
    # that differ in major version.
    { name = "windows-sys" },
]

[sources]
# Deny crates from unknown registries or git repositories.
unknown-registry = "deny"
unknown-git = "deny"
